{{- if .Values.installKitchensvcResillience -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-kitchensvc-virtual-service
spec:
  hosts:
    #- ordersvc-svc
  - restaurantsvc-kitchensvc
    #- restaurantsvc-restaurant-svc
  http:
  - route:
    # TODO fill in route0 which points to kitchensvc subset v0 here, and its traffic weight
    # should be 20%


    # TODO fill in route1 which points to kitchensvc subset v1 here, and its traffic weight
    # should be 80%
    name: "kitchensvc-v0"
    #match:
    #- uri:
    #    prefix: /ticket/create
{{- end -}}
